<?php 

return [
    'wilayah' => [
        'WILAYAH AMBON' => 'WILAYAH AMBON',
        'WILAYAH MAMUJU' => 'WILAYAH MAMUJU',
        'WILAYAH PALOPO' => 'WILAYAH PALOPO',
        'WILAYAH BONE' => 'WILAYAH BONE',
        'WILAYAH SIDRAP' => 'WILAYAH SIDRAP',
        'WILAYAH BULUKUMBA' => 'WILAYAH BULUKUMBA',
        'WILAYAH PINRANG' => 'WILAYAH PINRANG',
        'WILAYAH SINJAI' => 'WILAYAH SINJAI',
        'WILAYAH TORAJA' => 'WILAYAH TORAJA',
        'WILAYAH TAKALAR' => 'WILAYAH TAKALAR',
        'WILAYAH PANGKEP' => 'WILAYAH PANGKEP',
        'WILAYAH KENDARI' => 'WILAYAH KENDARI',
        'WILAYAH MUNA' => 'WILAYAH MUNA',
        'WILAYAH KOLAKA' => 'WILAYAH KOLAKA',
        'WILAYAH KONSEL' => 'WILAYAH KONSEL',
        'WILAYAH SOPPENG' => 'WILAYAH SOPPENG',
        'WILAYAH MASAMBA' => 'WILAYAH MASAMBA',
        'WILAYAH PARE-PARE' => 'WILAYAH PARE-PARE',
        'WILAYAH JAKARTA' => 'WILAYAH JAKARTA',
        'WILAYAH POLEWALI MANDAR' => 'WILAYAH POLEWALI MANDAR'
    ],
    'ekspedisi' => [
        'WILAYAH AMBON' => 'POS',
        'WILAYAH MAMUJU' => 'JNE',
        'WILAYAH PALOPO' => 'PANDUSIWI',
        'WILAYAH BONE' => 'JNE',
        'WILAYAH SIDRAP' => 'JNE',
        'WILAYAH BULUKUMBA' => 'JNE',
        'WILAYAH PINRANG' => 'JNE',
        'WILAYAH SINJAI' => 'JNE',
        'WILAYAH TORAJA' => 'JNE',
        'WILAYAH TAKALAR' => 'POS',
        'WILAYAH PANGKEP' => 'POS',
        'WILAYAH KENDARI' => 'POS',
        'WILAYAH MUNA' => 'JNE',
        'WILAYAH KOLAKA' => 'POS',
        'WILAYAH KONSEL' => 'POS',
        'WILAYAH SOPPENG' => 'JNE',
        'WILAYAH MASAMBA' => 'JNE',
        'WILAYAH PARE-PARE' => 'PANDUSIWI',
        'WILAYAH JAKARTA' => 'JNE',
        'WILAYAH POLEWALI MANDAR' => 'JNE'
    ]
];